spring:
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.17.254:3306/gunchim2?&serverTimezone=Asia/Seoul
    username: "user1"
    password: "1234"